### ISSUE TITLE
err.details.orig$ will be set to null ,if write code like this done('some string') 

### ISSUE THREAD

**Issue by peterli888** [rjrodger/eraro#2]
in "errormaker = function( ex, code, msg, details ) "
line 75:      ex         = null

this will lost some error message which not write as 'done(new Error("some string"))'.
so, err.details.orig$ will be null.
so, this may can be fixed as "//ex         = null" 
so, err.details.orig$  will be 'some string',this is more acceptable in some circumstance.

**Comment by bitmage** [comment]
[It's Node.js standard to use error objects](http://www.devthought.com/2011/12/22/a-string-is-not-an-error/).  Don't use strings, they have no stack context.

**Comment by peterli888** [comment]
thank you

Brandon Mason <notifications@github.com>于2016年7月1日周五 02:21写道：
